# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from processing.proto import tasks_pb2 as processing_dot_proto_dot_tasks__pb2


class TasksManagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTask = channel.unary_unary(
                '/TasksManager/GetTask',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=processing_dot_proto_dot_tasks__pb2.Task.FromString,
                )
        self.SubmitTask = channel.unary_unary(
                '/TasksManager/SubmitTask',
                request_serializer=processing_dot_proto_dot_tasks__pb2.SubmitTaskRequest.SerializeToString,
                response_deserializer=processing_dot_proto_dot_tasks__pb2.SubmitTaskResponse.FromString,
                )


class TasksManagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TasksManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTask': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTask,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=processing_dot_proto_dot_tasks__pb2.Task.SerializeToString,
            ),
            'SubmitTask': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitTask,
                    request_deserializer=processing_dot_proto_dot_tasks__pb2.SubmitTaskRequest.FromString,
                    response_serializer=processing_dot_proto_dot_tasks__pb2.SubmitTaskResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TasksManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TasksManager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TasksManager/GetTask',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            processing_dot_proto_dot_tasks__pb2.Task.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SubmitTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TasksManager/SubmitTask',
            processing_dot_proto_dot_tasks__pb2.SubmitTaskRequest.SerializeToString,
            processing_dot_proto_dot_tasks__pb2.SubmitTaskResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
