# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: processing/proto/tasks.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cprocessing/proto/tasks.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xba\x01\n\x04Task\x12\n\n\x02id\x18\x01 \x01(\x0c\x12\x16\n\x0e\x61udio_language\x18\x02 \x01(\t\x12\'\n\x0b\x61udio_files\x18\x03 \x03(\x0b\x32\x12.Task.AudioDetails\x12\x17\n\x0fremaining_count\x18\x04 \x01(\x03\x1aL\n\x0c\x41udioDetails\x12\x15\n\rfile_contents\x18\x01 \x01(\x0c\x12\x13\n\x0b\x64ocument_id\x18\x02 \x01(\x03\x12\x10\n\x08\x64uration\x18\x03 \x01(\x05\"\xb1\x01\n\x11SubmitTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\x0c\x12\x12\n\nmodel_used\x18\x02 \x01(\t\x12\x31\n\x07\x64\x65tails\x18\x03 \x03(\x0b\x32 .SubmitTaskRequest.AudioContents\x1a\x44\n\rAudioContents\x12\x13\n\x0b\x64ocument_id\x18\x01 \x01(\x03\x12\x10\n\x08language\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t\" \n\x12SubmitTaskResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x32o\n\x0cTasksManager\x12(\n\x07GetTask\x12\x16.google.protobuf.Empty\x1a\x05.Task\x12\x35\n\nSubmitTask\x12\x12.SubmitTaskRequest\x1a\x13.SubmitTaskResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'processing.proto.tasks_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TASK._serialized_start=62
  _TASK._serialized_end=248
  _TASK_AUDIODETAILS._serialized_start=172
  _TASK_AUDIODETAILS._serialized_end=248
  _SUBMITTASKREQUEST._serialized_start=251
  _SUBMITTASKREQUEST._serialized_end=428
  _SUBMITTASKREQUEST_AUDIOCONTENTS._serialized_start=360
  _SUBMITTASKREQUEST_AUDIOCONTENTS._serialized_end=428
  _SUBMITTASKRESPONSE._serialized_start=430
  _SUBMITTASKRESPONSE._serialized_end=462
  _TASKSMANAGER._serialized_start=464
  _TASKSMANAGER._serialized_end=575
# @@protoc_insertion_point(module_scope)
